{% set name = "belay" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/belay-{{ version }}.tar.gz
  sha256: d87c4074cef01b411d458a35ecf6a1c9beeb590389b1b0f16a98428d504996ae

build:
  entry_points:
    - belay=belay.cli.main:run_app
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.2.0
    - poetry-dynamic-versioning-plugin
    - python >=3.8,<4.0
  run:
    - aiohttp >=3.8.3,<4.0.0
    - autoregistry >=0.8.2,<0.9.0
    # From typer-all
    - colorama >=0.4.3,<0.5.0
    - fsspec >=2022.11.0,<2023.0.0
    - gitpython >=3.1.30,<4.0.0
    # Somehow this is needed for the CLI
    - packaging
    - pathspec
    - pydantic >=1.10.4,<2.0.0
    - pyserial >=3.1,<4.0
    - python >=3.8,<4.0
    - requests >=2.28.1,<3.0.0
    # From typer-all
    - rich >=10.11.0,<13.0.0
    # From typer-all
    - shellingham >=1.3.0,<2.0.0
    - tomli >=2.0.1,<3.0.0
    - typer >=0.6,<0.7
    - typing-extensions >=4.5.0,<5.0.0

test:
  imports:
    - belay
  commands:
    - pip check
    - belay --help
  requires:
    - git
    - pip

about:
  home: https://github.com/BrianPugh/belay
  doc_url: https://belay.readthedocs.io/
  summary: Rapid development of projects that interact with hardware via a micropython-compatible board.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
