{% set name = "belay" %}
{% set version = "0.22.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/belay-{{ version }}.tar.gz
  sha256: 88c68b59e1af2438072518ad2503a91f47aa1d77006a51d4f7590ef09ac37dd2

build:
  entry_points:
    - belay=belay.cli.main:run_app
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - python >=3.8.0,<4.0.0
  run:
    - python >=3.8.0,<4.0.0
    - pyserial >=3.1
    - typer >=0.6.0
    - pathspec >=0.10.3
    - tomli >=2.0.1
    - autoregistry >=0.10.1
    - fsspec >=2022.11.0
    - requests >=2.28.1
    - gitpython >=3.1.30
    - pydantic >=1.10.4
    - typing-extensions >=4.5.0
    - questionary >=2.0.0
    - packaging >=20.4
    - importlib_resources >=3.0.0

    # From typer-all
    - colorama >=0.4.3,<0.5.0
    - rich >=10.11.0,<13.0.0
    - shellingham >=1.3.0,<2.0.0

    # From fsspec-http
    - aiohttp !=4.0.0a0,!=4.0.0a1

    # From questionary 2.0.0
    - prompt_toolkit <=3.0.36,>=2.0

test:
  imports:
    - belay
  commands:
    # Disabling pip check for now because of autoregistry version error
    # belay 0.0.0.post91+798cd23 has requirement autoregistry>=0.10.1, but you have autoregistry 0.0.0.post18+eece474.
    # Probably have something to do with unexpected behavior related to the use of poetry-dynamic-versioning upstream in autoregistry
    # - pip check
    - belay --help
  requires:
    - git
    - pip

about:
  home: https://github.com/BrianPugh/belay
  doc_url: https://belay.readthedocs.io/
  summary: Rapid development of projects that interact with hardware via a micropython-compatible board.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
