{% set name = "belay" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/belay-{{ version }}.tar.gz
  sha256: 7f9f7ba70736d8a8d745e4c1bdd2be50b634deaaae715b98b3bc1911b7f7657e

build:
  entry_points:
    - belay=belay.cli.main:app
  noarch: python
  script:
    # Removing pyproject.toml here to prevent build from using poetry
    # because currently a dev version of poetry is required
    - {{ PYTHON }} -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<4.0
  run:
    - pathspec
    - pyserial >=3.1,<4.0
    - python >=3.8,<4.0
    - typer >=0.6,<0.7

test:
  imports:
    - belay
  commands:
    - pip check
    - belay --help
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/belay
  doc_url: https://belay.readthedocs.io/
  summary: Rapid development of projects that interact with hardware via a micropython-compatible board.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
