{% set name = "belay" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/belay-{{ version }}.tar.gz
  sha256: 7953d02a7e1cad9fd5879babde2de618f510d3d7ce47adb1c8251235c86fe1b0

build:
  entry_points:
    - belay=belay.cli.main:app
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.2.0
    - poetry-dynamic-versioning-plugin
    - python >=3.8,<4.0
  run:
    - autoregistry >=0.8.2,<0.9.0
    # From typer-all
    - colorama >=0.4.3,<0.5.0
    - httpx >=0.23.0,<0.24.0
    - packaging
    - pathspec
    - pyserial >=3.1,<4.0
    - python >=3.8,<4.0
    # From typer-all
    - rich >=10.11.0,<13.0.0
    # From typer-all
    - shellingham >=1.3.0,<2.0.0
    - tomli >=2.0.1,<3.0.0
    - typer >=0.6,<0.7

test:
  imports:
    - belay
  commands:
    - pip check
    - belay --help
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/belay
  doc_url: https://belay.readthedocs.io/
  summary: Rapid development of projects that interact with hardware via a micropython-compatible board.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
