{% set name = "belay" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/belay-{{ version }}.tar.gz
  sha256: 93dee195f9ad10ee8786a4cc50a9230950852290d3f155e6dde80101709d2513

build:
  noarch: python
  script:
    # Removing pyproject.toml here to prevent build from using poetry
    # because currently a dev version of poetry is required
    - {{ PYTHON }} -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - pyserial >=3.1,<4.0
    - python >=3.6,<4.0
    - typer >=0.6,<0.7

test:
  imports:
    - belay
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/belay
  doc_url: https://belay.readthedocs.io/
  summary: Rapid development of projects that interact with hardware via a micropython-compatible board.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
